# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Austin J. Green
title: Electrical And Computer Engineer
email: austinjgreen333@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username: AustinJGreen333
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: AustinGreen333
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Aboutme.png
about_content: | # this will include new lines to allow paragraphs
  Howdy, my name is Austin Green!

  I am a soon-to-be graduate with an Honors Bachelor of Science in Electrical and Computer Engineering from Oregon State University. After graduating, I am looking forward to starting a Ph.D. program in Applied Ocean Science at Scripps Institute of Oceanography in Fall 2023.  Much of my time as a student, employee, and just regular human, has been spent being involved in just about anything I could be. When it comes to my degree, my primary areas of interest were in Signals & Systems, and Robotics. I thoroughly enjoy the challenge that these areas provided and enjoy the nearly limitless applications they fit into. Thanks to some prior working and project experience, I am specifically interested in the Oceanic and Aviation industries. 

  Aside from that, I am a self-proclaimed wannabe jack-of-all-trades and am driven by a curiosity of understanding the world in new ways. I love working on a team and am more than comfortable admitting that I don't know everything, while always being willing to learn what it takes for me and my team to be successful.

  If you have any questions for me, or just want to chat, feel free to connect with me and I would be happy to talk!

  Thanks!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border:
          weak # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: Educational Ocean Drifter Kit
        link: https://github.com/greenaus/OSU_Ocean_Drifter
        link_text: Link to Project GitHub Repo
        additional_links:
          - title: Github Repository for project
            icon:
            url:
        quote: >
          Senior Honors Thesis
        description: | # this will include new lines to allow paragraphs
          For my Senior Thesis, I designed an ocean drifter parts kit, designed to be used in a Honors College class Fall of 2022. The focus of the kit was to introduce students of any major, to the field of oceanography and sensing. The requiremnts for the project were that it be low-budget and easy to use.

      - layout: top-middle
        border: weak
        title: Using ocean-going robots, to measure wave conditions
        link: https://eecs.engineering.oregonstate.edu/project-showcase/projects/?id=wGz7Z1E4AbLm16Rk
        link_text: Link to the Project Showcase Page
        additional_links:
          - title: Github Repository for project
            icon:
            url:
        quote: >
          Senior Capstone Project

        description: | #![alt text](/images/landscape-trees.jpg "Trees")


          My team and I were tasked with creating an independent sensing module to measure significant wave heights, while on deployments inside an Autonomous Underwater Vehicle (<mark>AUV</mark>). We utilized a 9-axis <mark>IMU</mark> to make the necessary acceleration data, and an <mark>STM32</mark> microcontroller to process that data into significant wave heights. Once processed, the data would be sent to the existing on board flight computer over <mark>RS232</mark>, and saved to an internal SD card backup.
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Medline Renewal
        sub_title: Collection Specialist
        caption: February 2022 - Present
        description: | # this will include new lines to allow paragraphs
          This is my current part-time position while in school. My main responsibilities are traveling between hospitals in my area, and collecting used single-use medical equipment to be reprocessed.

      - layout: left
        border: weak
        title: Oregon State University
        sub_title: Undergraduate Research Assistant
        caption: June 2021 - December 2021
        description: | # this will include new lines to allow paragraphs
          After finishing my Capstone project, I began working with the lab that sponsored the project. I continued work on the project in preparation for a research cruise they had coming up that it would be apart of.

          I was offered a spot on another research cruise they had planned, studying ocean mixing in the Gulf of Mexico. My primary role in this cruise was project and technical support, as well as overseeing drifter deployments and operation. During the cruise, I learned a lot about oceanography and how we study the ocean. I got the opportunity to work closely with professors, post-grads, and graduate students in the field, and assisted each them with their projects.

      - layout: left
        border: weak
        title: Oregon State University
        sub_title: Undergraduate Teaching Assistant
        caption: December 2018 - June 2021
        description: | # this will include new lines to allow paragraphs
          During my time as a TA, I assisted teaching a rotation of 3 introductory electrical engineering classes (ECE 111, ECE 112, and Engr 201). I oversaw lab and recitation sections for the respective courses, and was responsible for helping, assessing, and grading students in the courses. I primarily taught Lab safety, DC circuit analysis, and how to use common electrical engineering lab equipment.

      - layout: left
        border: weak
        title: FormFactor, Inc.
        sub_title: RF Test Engineering Intern
        caption: March 2020 - September 2020
        description: | # this will include new lines to allow paragraphs
          As an intern at FormFactor, I was a part of the RF Test Engineering Group. I was brought onto a project that had myself, and another intern, moving the company's test software from <mark>VBA</mark> to <mark>LabView</mark>. This was my primary project, and involved working with the technicians on the manufacturing line to ensure correct behavior. 

          Aside from that project, I was also tasked with assisting the senior engineers diagnosing probe failures in the Product Development Lab. These tasks introduced me to a lot of RF test equipment, and troubleshooting techniques. I primairly used a VNA to gather probe reflection charactersitics, and then learned how to interpret what the reflections could mean to provide the best solution to fixing the broken probe.

          The last project I was a part of, involved automating another section of the probe testing line. I wrote a C# program to load the correct calibration file on the technicians VNA, after entering the part number.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Oregon State University
        sub_title: Honors BSc Electrical and Computer Engineering
        caption: 2017 - 2022
        quote: >
          Focused on Robotics and Signals & Systems
        description: | # this will include new lines to allow paragraphs
          During my time at Oregon State University, I had the opportuninty to get involved in a variety of ways at the school. From an academic standpoint, I really enjoyed classes pertaining to Signals and Robotics. Outside of that, I was actively involved in other facets of the university as a student, employee, and club member. I participated in 24hr. Hackathons, class competions, and was an active member and officer in both the Robotics and Archery clubs.

          I started as the graphic designer for the OSU Robotics Club in my freshman year, then transitioned to the Marketing and PR Coordinator for the next 2 years. During my time in these positions, I oversaw and participated multiple community outreach events, as well as oversaw the creation of the Board of Business for the club to handle the funding and general administration needs of the club. 

          I also held the Safety Officer position in the OSU Archery Club. During my 3rd year, I had a friend approach me about restarting the inactive archery club at OSU. We became the new founding members, and oversaw all transportation, equipment usage, and safety training for all members.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not busy with work or school, I enjoy learning other skills and knowledge that are typically outside of my focus. Over the last couple of years, I have taught myself cooking, 3D modeling, and have self-studied oceanography, medical biology, and aviation. I have finished the ground school portion of a private pilot's license, and hope to begine flight lessons soon.

      Outside of the office or lab, I have grown to enjoy a lot of outdoor sports. I fell in love with rock climbing, long boarding, and snowboarding during my time at OSU. Aside from that, I really enjoy camping and hiking when I can get out, and before you ask, yes I love long walks on the beach.

      From a creative outlet standpoint, I am an avid tabletop gamer and have made many characters as well as been a Dungeon Master for 2 DND campaigns. I am currently also in the process of getting into videography. I plan to start documenting projects and hopefully posting them online here soon for others to be a part of.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
